### ISSUE TITLE
Chưa phải là live

### ISSUE THREAD

**Issue by Aragonbn90** [hoangdh/Huong-dan-cai-dat-stream-server-va-chuyen-doi-video-sang-streaming#1]
Bạn ơi, tiêu đề bài viết ghi là live stream, nhưng ở đây mình thấy bạn đang dùng các file nhạc có sẵn?
Bạn có thể cho mình biết cách để thu âm trực tiếp rồi gửi lên server ko?
Cảm ơn bạn.

**Comment by hoangdh** [comment]
Chào anh,

Cảm ơn anh đã quan tâm đến Livestream, a vui lòng tham khảo bài này ạ!

https://github.com/hoangdh/ghichep-StreamingVideo/blob/master/Setup-NGINX-RTMP.md
