### ISSUE TITLE
Phát video live stream bằng OBS hoặc phần mềm tương tự

### ISSUE THREAD

**Issue by GinCanhViet** [hoangdh/Huong-dan-cai-dat-stream-server-va-chuyen-doi-video-sang-streaming#2]
Chào bạn,
Cho mình hỏi thư viện này có hỗ trợ tạo steam key, để user add vào các phần mềm live stream, sau đó video đó đc phát trực tiếp trên website hay ko :D

Nếu lib này ko hỗ trợ, bạn có thể gợi ý cho mình các từ khóa hoặc gì đó để mình research ko.

Cảm ơn

**Comment by GinCanhViet** [comment]
Đại loại mình cần 1 live streaming server

**Comment by hoangdh** [comment]
Xin chào,

Để xây dựng một server livestream cơ bản, vui lòng tham khảo bài viết [này](https://github.com/hoangdh/ghichep-StreamingVideo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-Live-Stream-Server-s%E1%BB%AD-d%E1%BB%A5ng-NGINX-RTMP-tr%C3%AAn-Ubuntu)

## Cách đẩy stream:

Ví dụ, máy chủ của bạn là `192.168.1.234`
Khai báo với OBS: rtmp://192.168.1.234/live
Với `live`: là tên application trong phần [cấu hình ](https://github.com/hoangdh/ghichep-StreamingVideo/wiki/H%C6%B0%E1%BB%9Bng-d%E1%BA%ABn-c%C3%A0i-%C4%91%E1%BA%B7t-Live-Stream-Server-s%E1%BB%AD-d%E1%BB%A5ng-NGINX-RTMP-tr%C3%AAn-Ubuntu#24-c%E1%BA%A5u-h%C3%ACnh-hls-)

Và stream key là tùy ý, ví dụ: `gincanhviet`
Link play:
RTMP: rtmp://192.168.1.234/live/gincanhviet
HLS: http://192.168.1.234/live/gincanhviet/index.m3u8

Cảm ơn bạn đã quan tâm!

**Comment by GinCanhViet** [comment]
@hoangdh đã nghiên cứu, và thấy khả thi.
Cảm ơn bác nhé!

**Comment by namlq93** [comment]
@hoangdh b cho mình hỏi, muốn sài cái streaming video này mình phải tải video lên server của mình à bạn, nếu mình lấy url từ một nơi lưu trữ video khác rồi nhúng vô website thì có xử lý được không?

**Comment by hoangdh** [comment]
> @hoangdh b cho mình hỏi, muốn sài cái streaming video này mình phải tải video lên server của mình à bạn, nếu mình lấy url từ một nơi lưu trữ video khác rồi nhúng vô website thì có xử lý được không?

Chào Nam,

Dựa theo mô tả của bạn; thì đó là dạng VOD không phải là Livestream. Với mục đích là VOD, bạn có thể sử dụng [Nginx VOD](https://github.com/kaltura/nginx-vod-module) này,

Cảm ơn bạn đã quan tâm!
